# ===================================================================
# STAGE 1: The "Builder" - Installs runtime dependencies
# ===================================================================
FROM python:3.11-slim as builder

WORKDIR /app

# Install only the lightweight app dependencies into a clean environment.
# This creates a clean site-packages directory we can copy.
COPY requirements-app.txt .
RUN pip install --no-cache-dir -r requirements-app.txt


# ===================================================================
# STAGE 2: The "Final" - The lean production image
# ===================================================================
FROM python:3.11-slim

WORKDIR /app

# Copy the installed Python packages from the builder stage.
COPY --from=builder /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages

# Copy the installed executables (like gunicorn) from the builder stage.
COPY --from=builder /usr/local/bin /usr/local/bin

# Copy the application code and the assets generated by our GitHub Action.
# These files are expected to be in the build context.
COPY main.py .
COPY config.ini .
COPY recommendations.db .
COPY model.onnx .

# Set runtime environment variables
ENV WORKERS=2
ENV LOG_LEVEL=info

EXPOSE 8000

HEALTHCHECK --interval=30s --timeout=10s --retries=3 \
  CMD curl --fail http://localhost:8000/manifest.json || exit 1

# Run the app
CMD gunicorn -w $WORKERS -k uvicorn.workers.UvicornWorker main:app --bind 0.0.0.0:8000 --log-level $LOG_LEVEL
